# Generated by Django 5.0 on 2025-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistprofile",
            name="languages_of_lyrics",
            field=models.CharField(
                choices=[
                    ("english", "English"),
                    ("french", "French"),
                    ("both", "Both"),
                    ("English", "English"),
                    ("French", "French"),
                    ("Both", "Both"),
                ],
                max_length=10,
            ),
        ),
    ]
