# Generated by Django 5.0 on 2025-11-18 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_name_suggestions", models.TextField(blank=True, null=True)),
                ("taglines", models.TextField(blank=True, null=True)),
                ("visual_style", models.TextField(blank=True, null=True)),
                ("content_tone", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="songs/"),
                ),
                ("lyrics_text", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("french", "French"),
                            ("both", "Both"),
                        ],
                        default="english",
                        max_length=10,
                    ),
                ),
                ("tempo", models.FloatField(blank=True, null=True)),
                ("key", models.CharField(blank=True, max_length=10, null=True)),
                ("energy", models.FloatField(blank=True, null=True)),
                ("transcription", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captions", models.TextField(blank=True, null=True)),
                ("hashtags", models.TextField(blank=True, null=True)),
                ("flyer_text", models.TextField(blank=True, null=True)),
                ("short_video_scripts", models.TextField(blank=True, null=True)),
                ("streaming_links", models.TextField(blank=True, null=True)),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_content",
                        to="music.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleasePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_days", models.JSONField(default=list)),
                ("reminder_texts", models.JSONField(default=list)),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_plan",
                        to="music.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_input", models.TextField()),
                ("ai_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="music.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("virality_score", models.FloatField(default=0.0)),
                ("predicted_engagement", models.JSONField(default=dict)),
                ("ai_trends_insight", models.TextField(blank=True, null=True)),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="music.song",
                    ),
                ),
            ],
        ),
    ]
