# Generated by Django 5.0 on 2025-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialcontent",
            name="streaming_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialcontent",
            name="video_script",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aifeedback",
            name="ai_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="aifeedback",
            name="artist_input",
            field=models.TextField(blank=True, default=""),
        ),
    ]
