# Generated by Django 5.0 on 2025-11-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_socialcontent_streaming_text_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music_songs",
                to="users.artistprofile",
            ),
            preserve_default=False,
        ),
    ]
