# Generated by Django 5.0 on 2025-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_song_artist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aifeedback",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="aifeedback",
            name="ai_response",
        ),
        migrations.RemoveField(
            model_name="aifeedback",
            name="artist_input",
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="is_user_message",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="message",
            field=models.TextField(default="hey"),
            preserve_default=False,
        ),
    ]
